version: '3.5'

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports: 
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
