version: 2.1
jobs:
    test:
        docker:
            - image: cimg/ruby:3.1.3
              environment:
                BUNDLE_PATH: vendor/bundle
                RAILS_ENV: test
            - image: cimg/mysql:8.0
              name: db
              environment:
                  MYSQL_ROOT_PASSWORD: passw0rd
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "Gemfile.lock" }}
                    - v1-dependencies-
            # set up
            - run:
                name: install gems
                command:
                    bundle install
            - save_cache:
                paths:
                  - ./vendor/bundle
                key: v1-dependencies-{{ checksum "Gemfile.lock" }}
            - run:
                name: wait to setup db
                command: dockerize -wait tcp://db:3306 -timeout 1m
            - run:
                name: setup db
                command: bundle exec rails db:create db:schema:load
            # run test
            - run:
                name: run test
                command: bundle exec rspec --profile 10
            # run linter
            - run:
                name: run linter
                command: bundle exec rubocop
            # upload test result
            - store_test_results:
                path: test-results

workflows:
  sample:
    jobs:
      - test
