openapi: 3.0.3
info:
  title: minimal_api
  version: 1.0.0
servers:
  - url: http://localhost:3001
tags:
  - name: HealthChecks
    description: Endpoint to do healthchecks minimal_api
paths:
  /api/v1/healthchecks:
    get:
      tags:
        - HealthChecks
      summary: get success response
      operationId: healthCheck
      responses:
        '200':
          description: return result ok
          content:
            application/json:
              schema:
                required:
                  - result
                type: object
                properties:
                  result:
                    type: string
                    example: ok